const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://sugarspunrun.com/wp-content/uploads/2019/03/Best-buttermilk-pancake-recipe-14-of-16.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/htoyiqwv/c26dd28b-e700-42c9-89f3-fb6171e1a86d.jpg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAU8J0asBBqt81oSP5u59iOgVZo_GaNBvJNA&s",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_O1qxEyrBIvy9BsO_rbZeG8NGi7XsjYQPFA&s",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyJagA59abzd6XWANBqyPgCgswx6V3uwDhXA&s",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-2fXNZ1V0xo7Fhj50fysLxXLiJid0bYhoYQ&s",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREycTjD9wKrQNRlHJA1g4kFsycSQB7fqSRig&s",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://www.brugadabar.com/wp-content/uploads/2024/01/Traditional-American-Dish.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpEWLFJZDbjcujdZNeW4LQZqzT0uaFQbyVdg&s",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];

export default menu;
